// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxCaRXwCaKiFnnte8h20l_yV3OUTI5-_0',
    appId: '1:30091531054:web:c83be7de478d933cff20bf',
    messagingSenderId: '30091531054',
    projectId: 'chat-316a9',
    authDomain: 'chat-316a9.firebaseapp.com',
    storageBucket: 'chat-316a9.appspot.com',
    measurementId: 'G-LX1J39C4KG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyLPLvIZu08xdrpft7EFV0ScsbTQIstUE',
    appId: '1:30091531054:android:dd6e31112e75c098ff20bf',
    messagingSenderId: '30091531054',
    projectId: 'chat-316a9',
    storageBucket: 'chat-316a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0qIG2_mVLJdwRk0zNiUEDFZOJQyg3sRo',
    appId: '1:30091531054:ios:1fc2de2b5e0b198dff20bf',
    messagingSenderId: '30091531054',
    projectId: 'chat-316a9',
    storageBucket: 'chat-316a9.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0qIG2_mVLJdwRk0zNiUEDFZOJQyg3sRo',
    appId: '1:30091531054:ios:1fc2de2b5e0b198dff20bf',
    messagingSenderId: '30091531054',
    projectId: 'chat-316a9',
    storageBucket: 'chat-316a9.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
